name: app_tranporte_users
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Pacote para rotas com polilinhas
  flutter_polyline_points: ^1.0.0

  # Pacotes Firebase
  firebase_core: ^2.31.0  # Versão mais recente do firebase_core
  firebase_auth: ^4.19.5
  firebase_database: ^10.5.5
  firebase_storage: ^11.7.5

  # Firestore com versão mais recente compatível
  cloud_firestore: ^4.10.1

  # GeoFlutterFire compatível com Firestore mais recente
  geoflutterfire2: ^2.3.3  # Usando "geoflutterfire2" para funcionar com Firestore moderno

  # Google Maps
  google_maps_flutter: ^2.3.0

  # Geolocator para localização
  geolocator: ^9.0.2

  # Provider para gerenciamento de estado
  provider: ^6.0.4

  # Permissões do dispositivo
  permission_handler: ^10.2.0

  # Conectividade para verificar rede
  connectivity_plus: ^4.0.2

  # Ícones Cupertino para iOS
  cupertino_icons: ^1.0.6

  # Lançador de URL para ações como telefonar
  url_launcher: ^6.1.8

  # Pacote para reiniciar o app
  restart_app: ^1.2.1

  # Animação de carregamento
  loading_animation_widget: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  googleapis_auth: ^1.2.0  # Para autenticação com APIs do Google
  http: ^0.13.5
  flutter_geofire: ^2.0.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - themes/night_style.json
